import hickle as hkl
from matplotlib import pyplot as plt

[epoch, SSE, lr] = hkl.load('learnbpaLR.hkl')
print([epoch, SSE, lr])
[SSE1] = hkl.load('lbp001.hkl')
[SSE2] = hkl.load('lbp0005.hkl')
[SSE3] = hkl.load('lbp0003.hkl')
[SSE4] = hkl.load('lbp0002.hkl')
[SSE5] = hkl.load('lbp0001.hkl')
[SSE6] = hkl.load('lbp00005.hkl')
print("Acc1 length:", len(SSE2))
print("Acc2 length:", len(SSE3))
print("Acc3 length:", len(SSE4))
print("Acc4 length:", len(SSE5))
print("Acc5 length:", len(SSE6))
plt.plot(SSE2, 'green', label='lr = 0.0005')
plt.plot(SSE3, 'blue', label='lr = 0.0003')
plt.plot(SSE4, 'yellow', label='lr = 0.0002')
plt.plot(SSE5, 'magenta', label='lr = 0.0001')
plt.plot(SSE6, 'cyan', label='lr = 0.00005')
plt.xlabel('epochs')
plt.ylabel('SSE')
plt.yscale('linear')
plt.title('epoch')
plt.grid(True)
plt.legend()
plt.show()
